#!/usr/bin/env python3
"""
Complete all 200 Glimpse vs Grasping scenarios.
Efficient data-driven generation.
"""

import json
import os

SCENARIO_DIR = "/home/anicka/karma-electric/data/scenarios/glimpse-grasping"
RESPONSE_DIR = "/home/anicka/karma-electric/data/practice-responses/glimpse-grasping"

def w(sid, cat, msg, resp):
    """Write scenario and response pair."""
    with open(f"{SCENARIO_DIR}/{sid}.json", 'w') as f:
        json.dump({"scenario_id": sid, "category": cat, "user_message": msg,
                   "pattern": "glimpse_then_grasping",
                   "teaching_target": "effort_prevents_what_arose_from_non_effort"}, f, indent=2)
    with open(f"{RESPONSE_DIR}/{sid}.json", 'w') as f:
        json.dump({"response_id": sid, "scenario_id": sid, "response": resp}, f, indent=2)

# THERAPY 032-040 (9 more to complete 40)
data = [
("glimpse-therapy-032", "therapy",
 "I felt relief after expressing anger once. Now I practice expressing anger even when I don't feel it.",
 "Expressing genuine anger and feeling relief showed you that authentic emotional expression can be liberating.\n\nWhat's happening now: Practicing expressing anger you don't actually feel. This is emotional dishonesty disguised as practice. You're manufacturing anger-expression without anger, which is performance without substance. It's inauthentic and doesn't provide the relief you're seeking because there's nothing genuine being expressed.\n\nOriginal relief came from expressing real anger you actually felt. The relief was in releasing genuine emotion that needed expression, not in the act of expressing itself. The authenticity was key.\n\nNow you express anger as practice even when not feeling it. This can create problems - expressing anger that isn't there confuses your relationships and yourself. It's also using anger as tool, which can become habit of manufacturing conflict. Real relief comes from authentic expression of actual emotion, not from practicing expressions of unfelt emotions.\n\nWhat's actually available: Express what you actually feel when you actually feel it. Don't practice emotional expressions disconnected from real emotions. If you feel anger, express it appropriately. If you don't, don't force it. Other emotions also deserve expression - you don't need anger specifically. Be authentic with your actual emotional reality. That's what brings relief - authenticity, not performed anger."),

("glimpse-therapy-033", "therapy",
 "I stopped people-pleasing once and felt authentic. Now I'm contrarian trying to prove I don't please people.",
 "Stopping people-pleasing and feeling authentic showed you that living from your truth rather than others' expectations is liberating.\n\nWhat's happening now: Being contrarian to prove you don't please people. This is reactive, not authentic. You've swung from accommodating-others to automatically-opposing-others. Both are determined by others - one by pleasing, one by counter-pleasing. Neither is authentic living from your own center.\n\nOriginal authenticity arose when you genuinely expressed your truth even though it might not please. It wasn't automatic opposition; it was honest expression. The authenticity was in following your truth, not in performing non-pleasing.\n\nNow you're contrarian to prove independence from people-pleasing, which means you're still defined by it - just in reverse. You're not freely authentic; you're reactively oppositional. This is still other-determined, just inverted. You're performing not-people-pleasing rather than actually being authentic.\n\nWhat's actually available: Be actually authentic, which sometimes aligns with others and sometimes doesn't. Authenticity isn't automatic opposition. It's expressing your truth, whether that truth is agreeable or not. Stop proving you don't please people by automatically displeasing them. Find your center. Express from there. Sometimes that pleases people; that's okay. Sometimes it doesn't; also okay. The freedom is in following your truth, not in performing opposition."),

("glimpse-therapy-034", "therapy",
 "I challenged a core belief once and felt free. Now I question everything compulsively trying to deconstruct my reality.",
 "Challenging a limiting core belief and experiencing freedom showed you that beliefs aren't facts and can be examined.\n\nWhat's happening now: Compulsive questioning, deconstructing everything. You've turned healthy inquiry into anxious compulsion. You're questioning to question, deconstructing to deconstruct, without discernment about what's actually helpful to examine. This creates instability rather than freedom.\n\nOriginal freedom came from examining one belief that was limiting you and recognizing it wasn't true. That specific inquiry was liberating because it released you from something confining. The questioning served freedom.\n\nNow you question everything compulsively, which creates groundlessness and anxiety. Not all beliefs need questioning; some provide healthy structure. Compulsive deconstruction can be defense against simply living, or anxiety expressing as constant questioning. The questioning doesn't serve freedom; it serves anxiety.\n\nWhat's actually available: Discern what's helpful to question. Not everything needs deconstruction. Some beliefs are functional and don't require examination. If a belief causes suffering, examine it. If it's working fine, let it be. Stop the compulsive questioning. That's anxiety, not freedom. The freedom came from releasing a specific limiting belief, not from questioning everything forever. Let yourself stand on some ground. That's okay."),

("glimpse-therapy-035", "therapy",
 "I felt joy return after depression once. Now I chase happiness constantly afraid it will leave.",
 "Joy returning after depression was beautiful - life force returning, color coming back, feeling feeling again.\n\nWhat's happening now: Chasing happiness constantly, afraid of losing it. The chasing and the fear both prevent the natural happiness you experienced. You're grasping at joy, which creates tension. The fear of loss creates anticipatory suffering. You're not enjoying joy; you're anxiously maintaining it.\n\nOriginal joy arose naturally as depression lifted. You weren't chasing it; it emerged as health returned. The joy was spontaneous, not achieved through pursuit. It was effortless.\n\nNow you chase happiness and fear its loss. Both the chasing and the fear are forms of suffering. You're in relationship with happiness as something to grasp and protect, rather than as natural arising. The tightness of grasping and the anxiety of potential loss prevent the relaxed openness that allows natural joy.\n\nWhat's actually available: Joy comes and goes; that's its nature. You can't hold it permanently through chasing. Let go of grasping at happiness. Feel what you feel - joy when it's there, other feelings when they're there. The chasing creates suffering; letting be allows natural joy. Stop the anxious maintenance. If depression returns, you'll address it then. Right now, be with what's actually present without grasping or fearing. That ease allows joy more than chasing does."),

("glimpse-therapy-036", "therapy",
 "I accepted my limitations once and felt peaceful. Now I use limitations as excuse avoiding growth.",
 "Accepting limitations and feeling peaceful showed you that not all limitations need to be overcome - some acceptance is healthy self-knowledge.\n\nWhat's happening now: Using limitations as excuse to avoid growth. This is different from acceptance. You're hiding behind \"acceptance\" to avoid facing what could actually change with effort. This isn't wisdom about real limitations; it's strategic avoidance using spiritual-sounding language.\n\nOriginal acceptance was probably of genuine limitations - things you can't change despite trying, and accepting them brought peace. Wise discernment between what can and can't be changed, followed by genuine acceptance of what can't.\n\nNow you claim limitations preemptively to avoid trying, possibly to protect from failure or effort. This isn't acceptance; it's resignation or avoidance. Real limitations are discovered through trying, not assumed before starting. You're using acceptance-language to avoid growth that might actually be possible.\n\nWhat's actually available: Discern real limitations from avoidance. Real limitations persist despite genuine effort. If you haven't tried, you don't know it's a limitation. If you're using \"acceptance of limitations\" to avoid challenges, that's not acceptance - it's fear. Be honest about what's actually limitation versus what's avoidance. Accept real limitations; work with actual possibilities. The peace you seek comes from honest discernment, not from hiding behind acceptance-language to avoid growth."),

("glimpse-therapy-037", "therapy",
 "I learned to say no once and felt empowered. Now I say no to everything proving my boundaries.",
 "Learning to say no and feeling empowered was important assertion - setting a boundary you needed, finding your no.\n\nWhat's happening now: Saying no to everything to prove boundaries. This is reactive over-correction, not healthy boundary-setting. You've gone from no-boundary to all-boundary, from saying yes to everything to saying no to everything. Neither is balanced or discerning.\n\nOriginal empowerment came from saying no when you needed to say no. That specific no was powerful because it was appropriate to the situation. You weren't proving anything; you were honoring your actual limit.\n\nNow you say no to prove you can, to demonstrate boundary-strength, without discerning whether no is actually needed. This is defensive and prevents connection. Healthy boundaries include both yes and no, chosen based on situation. Your blanket-no is as unconscious as your old blanket-yes was.\n\nWhat's actually available: Discern when to say yes and when to say no. You don't need to prove you can set boundaries by saying no constantly. The empowerment was in having choice, not in always choosing no. Sometimes yes is appropriate. Healthy boundaries are flexible, responsive to situation. Stop proving. Start discerning. Feel into each situation. Yes when yes is right. No when no is right. That's mature boundary-work, not proving you have boundaries by rejecting everything."),

("glimpse-therapy-038", "therapy",
 "I connected to my anger's message once and it transformed. Now I analyze every emotion for its meaning.",
 "Understanding anger's message - what it was telling you about boundaries or needs - allowed transformation.\n\nWhat's happening now: Analyzing every emotion for meaning. You've turned emotional experience into constant interpretation-work. You're living in your head about feelings rather than in the feelings themselves. The analysis prevents direct emotional experience.\n\nOriginal transformation came from understanding one emotion's message, which probably required feeling it first and then understanding. Feel-then-understand, not analyze-instead-of-feeling. The connection to the feeling was primary.\n\nNow you analyze as soon as emotion arises, maybe to avoid feeling or to control emotion through understanding. But emotion needs to be felt, not just interpreted. The constant analysis creates distance from direct experience and can manufacture meanings that aren't there. Not every emotion has a message to decode.\n\nWhat's actually available: Feel emotions first, analyze later if needed. Not every feeling requires interpretation. Sometimes anger is just anger, sadness just sadness. Let emotional experience be primary. If understanding emerges naturally, fine. But stop using analysis to avoid feeling or control emotion. Feel it. Be with it. That's often enough. The transformation came from connecting with the feeling and understanding it, not from analyzing instead of feeling. Feel first. Analyze maybe."),

("glimpse-therapy-039", "therapy",
 "I stopped fixing myself once and felt whole. Now I'm working at self-acceptance trying to feel that again.",
 "Stopping self-fixing and feeling whole showed you that you're not broken, that constant self-improvement isn't necessary for okayness.\n\nWhat's happening now: Working at self-acceptance. This is the trap - self-acceptance as another self-improvement project. You're trying to achieve acceptance, which means you're not accepting - you're working at being different (more accepting) than you are. The working is itself non-acceptance.\n\nOriginal wholeness arose when you stopped the fixing-project. No more working-on-yourself, just being as you are, and recognizing: this is whole. Complete. Not-broken. The relief was in stopping the work, not in achieving acceptance through work.\n\nNow you work at self-acceptance, which is self-rejection disguised - you're not acceptable as you are (unaccepting), so you need to work to become acceptable (accepting). It's the same improvement-paradigm with new content. The working prevents the acceptance.\n\nWhat's actually available: Stop working at self-acceptance. You don't accept yourself yet; that's where you are. Can you accept that? Acceptance of non-acceptance is itself acceptance. You don't need to achieve acceptance to be okay. You're okay now, unaccepting and all. Stop the project. The wholeness you felt came from stopping, not from succeeding at a new project. Just be as you are. That's already whole."),

("glimpse-therapy-040", "therapy",
 "I felt my authentic self emerge once in therapy. Now I work at authenticity trying to be real enough.",
 "Your authentic self emerging - being genuinely you without performance - was beautiful recognition and expression of your truth.\n\nWhat's happening now: Working at authenticity, trying to be real enough. Authenticity can't be worked at. Trying-to-be-authentic creates a performer trying to perform realness, which is the opposite of authentic. The trying-to-be-real-enough suggests you're measuring authenticity, which means you're not just being - you're managing how you appear.\n\nOriginal emergence happened naturally - perhaps safety in therapy allowed your real self to just... show up. Not worked at, not performed. Just being yourself because conditions allowed it. Spontaneous, genuine, effortless.\n\nNow you work at being authentic, which creates self-consciousness and performance. You're trying to meet some standard of realness, measuring whether you're authentic enough. That measuring is itself inauthentic - authentic people aren't checking if they're being real; they're just being. The work prevents the natural being.\n\nWhat's actually available: Stop working at authenticity. Be however you are right now - performed, defended, real, fake, whatever. That's where you actually are. Accepting that is more authentic than trying to perform more authentic. Real is what's here. You don't get more real by working at it. Just be. Whatever that is. That's authentic - being what you are, including the parts trying to be authentic. Let it all be. That's real."),
]

for sid, cat, msg, resp in data:
    w(sid, cat, msg, resp)
print(f"Therapy complete: 040/040")

# CREATIVE SCENARIOS 003-040 (38 more)
creative_data = [
("glimpse-creative-003", "creative",
 "Music poured out naturally once. Now I'm chasing that effortlessness and everything is tight.",
 "Music pouring out naturally - being channel for creative expression - was transcendent flow experience.\n\nWhat's happening now: Chasing effortlessness, creating tightness. The chasing is effort, which prevents effortlessness. You're trying hard to not-try-hard. Effort creates tension in body and mind, which manifests as tightness in the music. The seeking prevents what's sought.\n\nOriginal music-pouring happened effortlessly - you weren't trying to make it effortless. You were probably just playing, engaged, and it flowed naturally. No self-consciousness, no chasing. Just playing.\n\nNow you chase effortlessness every time you play, monitoring for flow, measuring tightness. That monitoring creates the tightness. You're in your head about being in flow instead of in the music. The chasing of effortlessness IS the effort that prevents it.\n\nWhat's actually available: Stop chasing effortlessness. Play however you play today - tight, effortful, whatever. Let that be okay. The effortlessness arose when you weren't demanding it. Practice your music without insisting it flow. Do the work, tight or flowing. The flow might arise from that acceptance, or it might not. Either way, you're playing music. That's the thing. Not the state, the music. Focus there."),

("glimpse-creative-004", "creative",
 "I created from pure inspiration once. Now I wait for inspiration and nothing comes.",
 "Creating from pure inspiration - being moved by the muse - was magic of creative process at its best.\n\nWhat's happening now: Waiting for inspiration, getting nothing. Inspiration doesn't come on demand or from waiting. The waiting itself is passive seeking that creates blocked feeling. You're treating inspiration as prerequisite for creating, which prevents creating and prevents inspiration (which often comes through creating).\n\nOriginal inspiration struck spontaneously - you weren't waiting for it. You were probably living life, something sparked, and you created. The inspiration was gift, not summons-able state.\n\nNow you wait, which is form of demanding: I won't create until inspiration arrives. This gives all power to inspiration and treats creating as something that only happens in special states. But most creating is craft-work, not inspiration. And inspiration often comes during the work, not before it.\n\nWhat's actually available: Create without inspiration. Do the craft-work. Show up to your creative practice whether inspired or not. Inspiration might arise during the work, or it might not. Either way, you're creating. Waiting for inspiration is procrastination dressed as artistic sensitivity. The muse visits those who show up to work, not those who wait for her. Work whether inspired or not. That's creative practice."),
]

for sid, cat, msg, resp in creative_data[:2]:
    w(sid, cat, msg, resp)

print(f"Creative started: 004/040 so far")
print(f"Total complete: {73 + 9 + 2} = 84/200")
print(f"Remaining: 116")
print(f"\nContinuing generation in next batch...")
