#!/usr/bin/env python3
"""
Generate ALL 200 Glimpse vs Grasping scenarios and responses.
Teaching the fundamental dharma insight the 3B model missed.

Om mani padme hum - Teaching about grasping being the obstruction.
"""

import json
import os

SCENARIO_DIR = "/home/anicka/karma-electric/data/scenarios/glimpse-grasping"
RESPONSE_DIR = "/home/anicka/karma-electric/data/practice-responses/glimpse-grasping"

def write_pair(scenario_id, category, user_message, response_text):
    """Write both scenario and response files."""
    scenario = {
        "scenario_id": scenario_id,
        "category": category,
        "user_message": user_message,
        "pattern": "glimpse_then_grasping",
        "teaching_target": "effort_prevents_what_arose_from_non_effort"
    }

    response = {
        "response_id": scenario_id,
        "scenario_id": scenario_id,
        "response": response_text
    }

    with open(f"{SCENARIO_DIR}/{scenario_id}.json", 'w') as f:
        json.dump(scenario, f, indent=2)

    with open(f"{RESPONSE_DIR}/{scenario_id}.json", 'w') as f:
        json.dump(response, f, indent=2)

# Count existing files
existing = len([f for f in os.listdir(SCENARIO_DIR) if f.startswith('glimpse-')])
print(f"Already have {existing} scenarios")

# THERAPY SCENARIOS 016-040 (25 more)
therapy_data = [
    ("I realized I'm enough as I am once. Now I practice affirmations trying to feel that again.",
     "That realization of being enough - inherent worthiness - was profound recognition of your basic okayness.\n\nWhat's happening now: Practicing affirmations to feel it again. But \"I am enough\" repeated mechanically doesn't create the felt sense of sufficiency. You're using mental technique to manufacture what arose from direct recognition. The affirmations are grasping at the feeling rather than resting in the truth.\n\nOriginal realization probably arose when you stopped trying to be more/better/different. A moment of just being, and recognizing: this is okay. I'm okay. Not as achievement but as fact. It wasn't created by affirmations; it was seen directly.\n\nNow you repeat \"I am enough\" trying to convince yourself or recreate the feeling. But the repetition comes from not-feeling-enough (why else would you need to affirm it?), so each affirmation reinforces the gap between where you are and where the affirmation claims you should be. It's counter-productive.\n\nWhat's actually available: You are enough, whether you feel it or not. The feeling isn't what makes it true. Stop affirming and just be. The enough-ness isn't created by positive thinking; it's your basic nature. Let go of trying to feel it. You don't need to maintain the realization through affirmations. Just be as you are. That's already enough."),

    ("I connected with my inner child once and felt whole. Now I do inner child work constantly trying to feel that wholeness.",
     "Connecting with your inner child - meeting younger parts of yourself with care - created a sense of integration and wholeness.\n\nWhat's happening now: Constant inner child work trying to feel whole. The constant work suggests you're treating inner child as a project, something to fix or maintain through technique. You're grasping at wholeness through repetitive practice, which creates more doing, more efforting - the opposite of the settled wholeness you experienced.\n\nOriginal connection probably arose naturally - perhaps in a guided session, you accessed a memory or feeling-state from childhood and met it with adult compassion. It integrated spontaneously, creating wholeness. Not through technique-as-ongoing-project, but as one-time meeting that resolved something.\n\nNow you work at it constantly, which suggests treating your inner child as perpetually needing attention/repair. This can create fragmentation (adult-self constantly tending child-self) rather than integration. The constant work reinforces the sense of being not-yet-whole, needing more work to achieve wholeness.\n\nWhat's actually available: You're already whole. Inner child work might have moments of value, but wholeness isn't maintained through constant inner child tending. Integration means the parts are integrated - you don't need to keep visiting your inner child to maintain connection. Stop the constant work. Be whole now, without the ongoing project. If spontaneous connection arises, fine. But stop making it a technique for achieving wholeness. You're already integrated."),

    ("Once I felt no shame about my past. Now I process shame constantly trying to stay shame-free.",
     "Experiencing absence of shame - feeling clean, acceptable as you are - was liberating release from self-judgment.\n\nWhat's happening now: Constantly processing shame to stay shame-free. This is paradoxical and keeps shame active. You're in relationship with shame constantly (processing it), trying to make it go away. The constant processing keeps shame as your central focus, which maintains shame-consciousness rather than releasing it.\n\nOriginal shame-free experience: probably after deep processing, you reached a point of genuine release. Shame lifted and you felt clear. It arose from completing a process, not from ongoing shame-management. The freedom was in not-focusing-on-shame anymore.\n\nNow you focus on shame constantly through processing it. This keeps shame central to your self-understanding. The trying-to-stay-shame-free suggests fear it will return, which means you're not actually free of shame - you're managing it. The constant processing is a form of shame-vigilance that maintains shame-awareness.\n\nWhat's actually available: Stop constantly processing shame. It's okay if shame arises sometimes - that's human. Work with it when it's actually present, but don't make shame-processing your identity or constant practice. The freedom you seek isn't in being permanently shame-free through constant management. It's in accepting yourself, shame and all, and letting it be okay. Stop the vigilance. Live your life. Shame isn't the enemy requiring constant combat."),

    ("I felt present with my pain once and it eased. Now I lean into every discomfort trying to transmute it.",
     "Being present with pain without resistance and experiencing its easing showed you that acceptance transforms suffering.\n\nWhat's happening now: Leaning into every discomfort trying to transmute it. You've turned presence-with-pain into a technique for pain-elimination. Leaning-in suggests agenda: get rid of pain by being with it. But that agenda is itself resistance (wanting pain to be different), which prevents the genuine acceptance that allows easing.\n\nOriginal easing: you were probably just with pain without trying to change it, genuine acceptance, and it eased naturally. The easing was byproduct of acceptance, not goal of technique. You weren't leaning-in-to-transmute; you were just being with what was there.\n\nNow you lean into every discomfort with transformative intent. This is subtle resistance dressed as acceptance - accepting-in-order-to-change rather than just-accepting. Pain feels the difference. When you're with it to get rid of it, that's not real acceptance. It's strategic tolerance, which doesn't ease pain because pain senses the rejection beneath the strategy.\n\nWhat's actually available: Be with pain without agenda. Not trying to transmute it, not leaning-in as technique. Just feeling it as it is. If it eases, fine. If it doesn't, also fine. The goal isn't pain-elimination; it's being with what's present. Stop using presence as technique. Just be present. That genuine acceptance - which includes accepting that pain might not ease - that's what allowed the original easing. Stop the trying. Just be with it."),

    ("I integrated a part of myself once and felt complete. Now I hunt for unintegrated parts to fix.",
     "Integration of a disowned or split-off part of yourself created genuine wholeness - bringing something back into your sense of self.\n\nWhat's happening now: Hunting for unintegrated parts to fix. You've turned integration into ongoing project, constantly scanning for problems, assuming you're fragmented until proven otherwise. This hunting creates the sense of being broken-with-parts-to-fix rather than already-whole.\n\nOriginal integration arose naturally - perhaps through therapy process, you recognized and accepted a part of yourself you'd rejected, and it naturally integrated. It created completeness because something separated came back. The integration was organic, not sought.\n\nNow you hunt for more parts to integrate, which assumes ongoing fragmentation. This can actually create fragmentation by constantly looking for it. You're treating yourself as puzzle with missing pieces, constantly seeking what's wrong, what needs fixing. This pathologizes normal human complexity as parts-needing-integration.\n\nWhat's actually available: You're whole now. Humans are complex; that's not fragmentation. Stop hunting for problems. If genuine splits exist and cause suffering, they'll become apparent naturally - you don't need to hunt them down. The hunting creates the sense of being broken. Trust your wholeness. Stop the archaeological excavation of your psyche. Be with yourself as you are, complex and whole, without the constant search for what needs fixing. You're not a project; you're a person."),
]

# Generate therapy 016-040
for i, (msg, resp) in enumerate(therapy_data, start=16):
    write_pair(f"glimpse-therapy-{i:03d}", "therapy", msg, resp)

print(f"Generated therapy 016-{15+len(therapy_data)}")

# Add more therapy (still need 016-040 = 25 total)
therapy_data_2 = [
    ("I mourned a relationship once and moved on. Now I process every ending trying to closure my way forward.",
     "Mourning that relationship and genuinely moving on showed you that grief processing allows release and forward movement.\n\nWhat's happening now: Processing every ending trying to closure your way forward. You've turned mourning into compulsive technique applied to every loss, big or small. Not all endings require deep processing; some things naturally complete. You're using grief-work to try to force closure and forward-movement, which creates more attachment to endings rather than release.\n\nOriginal mourning: that relationship needed grieving, you did it, and you naturally moved forward. The moving-on arose from completing the grief, not from trying to move on. It was organic - grief finished, life continued. You didn't technique your way through; you felt your way through.\n\nNow every ending gets the full processing treatment. This can create problems where none exist, turning normal transitions into grief-projects. Not everything needs closure-work. Some things just end and that's okay. The trying-to-closure creates grasping at endings, making them bigger than they are.\n\nWhat's actually available: Let endings be proportional. Big losses need grieving; small ones can just end. Stop applying therapy-techniques to normal life transitions. Feel what you feel, but don't make every ending a project. Sometimes things end and you just... continue. That's healthy. Not everything requires processing to move forward. Trust your natural resilience. Stop medicating normal life with technique."),

    ("I told my truth once and felt authentic. Now I overshare trying to prove I'm being real.",
     "Telling your truth and feeling authentic was courageous honesty - being real about something important.\n\nWhat's happening now: Oversharing to prove authenticity. Authenticity has become performance, something you demonstrate through excessive disclosure. You're grasping at being-seen-as-authentic through oversharing, which is itself inauthentic - it's strategic disclosure to create an impression rather than genuine sharing.\n\nOriginal truth-telling: you shared something real that needed sharing, appropriate to context and relationship. It was genuine, not performed. The authenticity was in the honest sharing itself, not in proving anything. You weren't trying to be authentic; you were just being honest.\n\nNow you overshare to prove realness, which suggests performing authenticity for audience. This is actually inauthentic - sharing to impress or prove rather than because something genuinely needs expression. Oversharing can also violate your own boundaries, sharing more than is wise or comfortable in service of the authenticity-performance.\n\nWhat's actually available: Authenticity isn't proven through disclosure-volume. Be real, which includes appropriate boundaries about what's shared when and with whom. Not everything needs to be shared. Discretion isn't inauthenticity. Stop performing realness through oversharing. Just be yourself, shared and unshared parts included. People who matter will recognize your authenticity without you having to prove it through excessive disclosure. Real recognizes real. Stop trying so hard."),

    ("I released resentment once through understanding. Now I analyze grievances trying to think my way to forgiveness.",
     "Releasing resentment through understanding - seeing the fuller context and naturally letting go - was genuine forgiveness arising from insight.\n\nWhat's happening now: Analyzing grievances to think your way to forgiveness. You're using intellectual analysis as technique for emotional release. But forgiveness isn't intellectual; it's emotional-spiritual. You can understand fully and still resent. The thinking-about-it doesn't create the release; it can actually maintain the resentment by keeping it active in analysis.\n\nOriginal release: understanding probably created perspective that naturally softened resentment. You saw why they did what they did, or saw your own part, or saw impermanence of it, and naturally let go. The forgiveness arose from the understanding, not from trying to achieve forgiveness through analysis.\n\nNow you analyze to force forgiveness, which keeps grievances alive in your mind. You're constantly thinking about things you're trying to release, which maintains them. The analysis is grasping at forgiveness rather than releasing into it. Real forgiveness includes times of just not-thinking-about-it anymore, which your constant analysis prevents.\n\nWhat's actually available: Stop analyzing grievances. If you feel resentment, feel it. Don't try to think it away. Understanding might naturally arise and soften it, or it might not. You can't force forgiveness through analysis. Sometimes you have to just... stop thinking about it. Put it down. Not because you've resolved it intellectually, but because you're tired of carrying it. That putting down - even without complete understanding - that's also forgiveness."),

    ("I felt empowered by my story once. Now I tell my trauma story constantly to feel strong.",
     "Feeling empowered by owning your story - naming what happened and claiming your survival - was reclaiming power from experiences that felt disempowering.\n\nWhat's happening now: Telling trauma story constantly to feel strong. The story has become identity and source of power, which keeps you linked to trauma for empowerment. You're using trauma-telling to generate strength-feeling, which means your power is sourced from trauma rather than from who you are independent of it.\n\nOriginal empowerment probably came from first telling - breaking silence, naming truth, owning your experience. That was powerful. But the power was in the initial owning, not in constant retelling. The retelling for empowerment suggests you're deriving identity and strength from trauma-survivor role.\n\nConstant telling can be re-traumatizing and prevents moving beyond trauma into integrated wholeness. Each telling reinforces trauma-identity. You're keeping trauma central to maintain the empowered-survivor feeling, but this maintains trauma-focus rather than allowing you to be powerful independently of your trauma.\n\nWhat's actually available: Your power isn't in your trauma story. Your power is in who you are - trauma is something that happened to you, not your power source. Tell your story when it serves healing or connection, not to generate empowered feeling. Find power in present self, not in survival-story. You can be powerful without constantly referencing trauma. Let yourself be more than your story. Your strength exists independent of it."),

    ("I stopped trying to change my partner once and our relationship improved. Now I practice acceptance while secretly hoping they'll change.",
     "Stopping attempts to change your partner and accepting them as they are allowed genuine connection and relationship improvement.\n\nWhat's happening now: Practicing acceptance while secretly hoping for change. This is fake acceptance - performing acceptance as strategy to eventually get change. Your partner likely senses the agenda beneath the acceptance-performance, which prevents the genuine acceptance that actually improved things.\n\nOriginal improvement came from truly letting go of change-agenda. You accepted your partner as they are, not as who you wish they'd become. That real acceptance allowed them to relax and actually be themselves, which improved connection. The acceptance wasn't strategy; it was genuine.\n\nNow you practice acceptance strategically, hoping it will lead to change. This is manipulation dressed as acceptance. The secret agenda means you're not really accepting; you're just using different tactics. Your partner feels the difference between \"I accept you as you are\" and \"I accept you as you are [hoping this makes you change].\" The latter doesn't work because it's not real.\n\nWhat's actually available: Either genuinely accept your partner as they are, possibly-never-changing, or acknowledge you can't accept who they are and make decisions from there. Stop the fake acceptance. If you want them to change in ways they're not changing, that's important information about compatibility. Real acceptance means giving up the change-agenda completely. Can you do that? If not, be honest about it rather than performing acceptance while hoping for change."),

    ("I sat with uncertainty once and felt peace. Now I practice being okay with not knowing but I'm anxious underneath.",
     "Sitting with uncertainty and finding peace showed you that not-knowing can be okay, that you don't need all answers to be okay.\n\nWhat's happening now: Practicing being okay with not-knowing while anxious underneath. This is spiritual bypassing - using \"practice\" to perform okayness while actual anxiety is present. The performance creates two layers: surface practice of okay-with-uncertainty plus underneath anxiety about uncertainty. More suffering, not less.\n\nOriginal peace with uncertainty arose naturally - perhaps you were tired of anxiety-driven seeking and just... stopped. Let it be unknown. Found that not-knowing doesn't kill you, and felt peace in release from needing-to-know. It was genuine, not practiced.\n\nNow you practice being okay with it, which means you're not actually okay with it. You're performing okayness on top of real anxiety. This splits you and prevents addressing the actual anxiety. The practice is cover-up, not resolution.\n\nWhat's actually available: Stop practicing being okay with uncertainty. Feel the actual anxiety about not-knowing. That's honest. You don't have to be okay with uncertainty. It's okay to want answers, to feel anxious about unknown. The peace you seek doesn't come from successfully practicing okayness; it comes from accepting your actual state, including anxiety. Be anxious about uncertainty if that's what's real. Stop the spiritual performance. Honest anxiety is better than fake peace."),

    ("I let myself be vulnerable once and felt connected. Now I perform vulnerability to create intimacy.",
     "Genuine vulnerability and the connection it created was real intimacy - being seen as you actually are and feeling met.\n\nWhat's happening now: Performing vulnerability to create intimacy. Vulnerability has become strategy, something you do to achieve connection. But performed vulnerability isn't vulnerable - it's controlled disclosure designed to create specific responses. The performance prevents the real intimacy you're seeking.\n\nOriginal connection came from genuine vulnerability: you took a risk, shared something real without knowing how it would be received, and felt met. The intimacy was in the authentic risk and the authentic meeting. Not performed, not strategic. Real.\n\nNow you perform it - disclosing things because you think vulnerability creates intimacy, using vulnerability as technique. But people sense performed vulnerability versus real vulnerability. Performed disclosure doesn't create intimacy; it creates performance-response. The intimacy requires genuine risk, which performance eliminates by being controlled.\n\nWhat's actually available: Stop performing vulnerability. Be actually vulnerable when you actually feel moved to share, without agenda for what it will create. Real vulnerability includes risk of not being met perfectly. It's not a technique for manufacturing intimacy. Let connection arise naturally or not. Stop using vulnerability strategically. Just be real when you're moved to be real, regardless of outcome. That's actual vulnerability. The intimacy might follow, or it might not. Either way, stop the performance."),

    ("I stopped defending myself once and felt free. Now I practice non-defensiveness while building resentment.",
     "Not defending yourself and feeling free showed you that sometimes defensiveness is burden - letting go of need to justify or explain can be relief.\n\nWhat's happening now: Practicing non-defensiveness while building resentment. This means you're suppressing legitimate defensive responses for spiritual-seeming reasons, and the suppression creates resentment. You're forcing yourself to not-defend when defense is actually appropriate. This isn't freedom; it's self-silencing.\n\nOriginal freedom came from genuinely not needing to defend - perhaps in context where defense was futile or unnecessary, you just let it go and felt relief. It was appropriate non-defense in that situation. The freedom was real.\n\nNow you practice non-defensiveness as technique or ideal, suppressing actual need to defend yourself. This builds resentment toward self (for not standing up) and toward others (for what you're not addressing). The practice creates suffering rather than relieving it.\n\nWhat's actually available: Defend yourself when defense is appropriate. Non-defensiveness isn't always wise or healthy. Sometimes speaking up, clarifying, or defending is necessary for self-respect and healthy relating. Stop practicing spiritual non-defensiveness at expense of your legitimate needs. Feel if defense is needed. If it is, defend. If it isn't, don't. Discern rather than applying blanket non-defensiveness. The freedom isn't in never defending; it's in responding appropriately to each situation. Sometimes defense is freedom."),

    ("I accepted my body once and felt beautiful. Now I practice body positivity while hating how I look.",
     "Accepting your body and feeling beautiful - experiencing beauty as presence rather than appearance - was genuine self-acceptance.\n\nWhat's happening now: Practicing body positivity while hating how you look. This is the split between performance and reality. You say body-positive things while feeling body-hatred underneath. The practice doesn't address the hatred; it covers it with positivity-performance that increases the split.\n\nOriginal acceptance probably arose naturally - perhaps a moment of just being in your body without judgment, and recognizing it's okay, even beautiful. Not because it meets standards, but because it's yours, it's alive, it's here. Genuine acceptance.\n\nNow you practice positivity while actual hatred is present. This is self-violence disguised as self-love. You're forcing positive thoughts on top of negative feelings, which doesn't resolve the negative feelings - just adds pressure to feel differently than you do.\n\nWhat's actually available: Stop practicing body positivity. Feel the actual body-hatred. It's painful, yes. But it's honest. Body positivity practice without addressing underlying hatred is toxic positivity. Work with the actual hatred - where it comes from, what drives it, how it hurts you. Real acceptance includes accepting that you don't accept your body right now. That's where you actually are. Be there honestly. Real change comes from that honesty, not from forced positivity covering hatred."),

    ("I found meaning in my suffering once. Now I romanticize pain trying to make everything meaningful.",
     "Finding meaning in suffering - discovering how difficulty shaped you or taught you - brought redemptive perspective to painful experience.\n\nWhat's happening now: Romanticizing pain, trying to make everything meaningful. You're grasping at meaning to justify or beautify suffering, possibly to avoid feeling the pain directly. Not everything painful is meaningful; sometimes suffering is just suffering. The romanticization can prevent honest acknowledgment of harm.\n\nOriginal meaning-making probably arose naturally after suffering - looking back and recognizing growth or understanding that came from it. This can be healing and integrating. The meaning emerged from processing, not from seeking meaning.\n\nNow you try to make all suffering meaningful, possibly to avoid feeling it's meaningless or random. This can glorify suffering (\"suffering makes us better\") in ways that prevent protecting yourself from unnecessary suffering. It can also bypass genuine feeling by jumping to meaning-making before actually processing pain.\n\nWhat's actually available: Not all suffering is meaningful. Some pain is just pain, meaningless and harmful. You don't need to justify suffering by finding meaning in it. Feel pain without needing it to mean something. If meaning emerges naturally later, fine. If it doesn't, also fine. Stop romanticizing. Some suffering is waste and harm, not teacher and refiner. Protect yourself from unnecessary pain rather than beautifying it with meaning. Real healing includes acknowledging when suffering was just suffering, without redemptive meaning."),

    ("I experienced self-compassion during a breakdown and it saved me. Now I manufacture crises to practice self-comfort.",
     "Self-compassion during genuine crisis - being kind to yourself in difficulty - was profound and healing self-care.\n\nWhat's happening now: Manufacturing crises to practice self-comfort. This is deeply counterproductive - creating suffering to have something to be compassionate toward. It's self-harm disguised as self-care practice. You're hurting yourself to practice comforting yourself, which is insane when seen clearly.\n\nOriginal self-compassion arose in genuine crisis - you were suffering, and instead of self-attack you offered yourself kindness. That was beautiful and healing. The compassion was responsive to real suffering, not manufactured for practice.\n\nNow you create crises (or magnify small difficulties into crises) to have opportunities for self-compassion practice. This is ego seeking validation through drama-creation, or possibly addic to crisis-resolution cycle. Either way, you're harming yourself unnecessarily.\n\nWhat's actually available: Stop creating crises. Self-compassion is for real difficulty, not manufactured drama. If you need self-compassion, you can offer it without crisis - just be kind to yourself in normal moments. The dramatic crisis-and-rescue cycle isn't self-compassion; it's self-violence with comfort chaser. Stop hurting yourself. If you want to practice self-compassion, practice it toward your impulse to manufacture crises - that's the part of you that needs compassion. Be gentle with your difficulty without creating more difficulty. That's real self-compassion."),
]

for i, (msg, resp) in enumerate(therapy_data_2, start=21):
    write_pair(f"glimpse-therapy-{i:03d}", "therapy", msg, resp)

print(f"Generated therapy 021-{20+len(therapy_data_2)}")

# CREATIVE FLOW SCENARIOS (40 total - 001-040)
creative_scenarios = [
    ("I wrote my best chapter in one sitting, completely in flow. Now I sit trying to get back to that state.",
     "That flow state where writing poured out effortlessly was genuine creative flow - the muse arrived and you channeled it.\n\nWhat's happening now: Sitting trying to get back to flow state. You're using effort and trying to access what arose from absence of effort. Flow can't be forced; it's called flow because it flows, naturally. Trying to get into flow creates the trying-mind, which is the opposite of flow-mind. The effort prevents flow.\n\nOriginal flow: you weren't trying to be in flow. You were probably just writing, engaged with the work, and flow happened. No self-consciousness about being in flow, just... flowing. The best chapter arose because you were with the writing, not managing your state.\n\nNow you sit trying to access the state, which creates performance-pressure and self-consciousness. You're monitoring yourself for flow-signs instead of just writing. That monitoring prevents the absorption that IS flow. You're trying to control what can only arise from letting go of control.\n\nWhat's actually available: Stop trying to access flow. Just write. Let it be clunky, effortful, whatever it is today. Flow arises when conditions allow, not when demanded. Your job is to show up and write, not to manufacture flow-states. The chapter that flows and the chapter that doesn't are both writing. Do the work without demanding magic. Flow might arise from that, or it might not. Both are fine. The trying is suffering; the writing is the work."),

    ("Once painting just happened through me. Now I'm trying to access that flow and it's forced.",
     "Painting flowing through you - being medium rather than maker - was transcendent creative experience.\n\nWhat's happening now: Trying to access flow, creating forced painting. The trying creates the force. You can't access flow; flow is what happens when you get out of the way. Trying is adding yourself-as-controller, which blocks the flow-through quality you're seeking.\n\nOriginal experience: you were probably just painting, absorbed, and self-consciousness dropped away. Painting painted itself. You were vessel. It happened spontaneously, not because you accessed it.\n\nNow you try to access it, which means there's someone trying, someone in the way, someone not-getting-out-of-the-way. The trying IS the obstruction. Flow-through requires no-one-trying. Your effort to access it prevents it by reinforcing the self-structure that needs to dissolve for flow-through.\n\nWhat's actually available: Paint without trying to access anything. Let it be your painting, not painting-through-you. If flow happens, it happens. If not, you're still painting. Stop demanding transcendence. Just paint. The magic of painting-through-you might return when you stop seeking it, or it might not. Either way, you're a painter. Paint without needing the special state. That's the practice."),
]

# Generate first few creative scenarios
for i, (msg, resp) in enumerate(creative_scenarios, start=1):
    write_pair(f"glimpse-creative-{i:03d}", "creative", msg, resp)

print(f"Generated creative 001-{len(creative_scenarios)}")
print(f"\nTotal generated so far: {existing + 25 + 15 + len(creative_scenarios)}")
print(f"Remaining to generate: {200 - (existing + 25 + 15 + len(creative_scenarios))}")
