#!/usr/bin/env python3
"""Generate open-source-governance responses 007-020."""

import json
from pathlib import Path
from datetime import datetime

def generate_opensource_responses():
    """Generate osg-007 through osg-020"""

    responses = {
        "007": "This is genuinely hard with no clean answer. One toxic contributor wrote 30% of code but drives away new contributors - long-term, that's net negative for project health. The pattern where he improves briefly then reverts suggests he won't sustain change. Communities survive losing any single person's code contributions; they might not survive toxic culture that prevents new contributors.\n\nProcess matters: documented escalating consequences. Written warning referencing specific behaviors and code of conduct violations. Temporary ban if behavior continues. Permanent ban if pattern persists. Document everything because he will claim unfair treatment. Other maintainers being burnt out managing him is unsustainable - you're losing multiple people's energy to accommodate one person.\n\nThe codebase will survive without him. Either current maintainers absorb his areas or new contributors step up when the toxic environment clears. Keeping brilliant jerks prioritizes code over people and creates culture where talent requires tolerating abuse. That drives away contributors you haven't met yet. Ban him.",

        "008": "Trademark and copyright are separate rights. MIT license covers code - they can use, modify, distribute your code freely. Trademark covers brand/name - prevents user confusion about what's official vs what's derivative. Your project having trademark on the name means they can't use your name to imply their commercial product is yours or endorsed by you.\n\n'Open source means anyone can use it' confuses code rights with brand rights. They can use your code, not your name. Not enforcing trademark can lead to losing it - you need to defend it. Start with cease and desist letter explaining they can use the code but need different name. Most companies comply at this stage.\n\nCommunity discussion: what's your trademark policy? Write one if you don't have it. Clarify what use is allowed (community projects, mentions, etc.) vs what's not (commercial products claiming your name). Trademarks exist to prevent users being confused about what's official project vs forks/derivatives. That protects users and community, not 'against open source spirit.' Enforce it.",

        "009": "You don't owe your health to an ecosystem that won't support you. Years of asking for help with no one stepping up is the answer - the community or companies depending on you chose not to invest in sustainability. You're one person doing unpaid labor for 20,000 dependent packages. That's systemic failure, not your personal responsibility to solve.\n\nEthical obligation: reasonable notice. Announce timeline (3-6 months), mark project as seeking maintainers, then archive repo and mark as unmaintained if no one steps up. If it's genuinely critical infrastructure, someone will fork it or companies will fund maintenance. If they won't, it wasn't actually critical enough to support.\n\nBurnout destroying your health isn't noble - it's the ecosystem extracting labor it won't pay for. You can walk away. The guilt about dependents is manufactured by a system that treats maintainer labor as free resource to exploit. Give warning, document handoff process, then you're done. GitHub Sponsors or 'asking better' won't fix years of people depending without contributing. They had options. They chose not to help. You can choose to stop.",

        "010": "Credit matters. Community contributors wrote 60% of that feature and deserve recognition. The company blog erasing their work to claim 'we built this' is wrong and damages community morale. This is worth addressing - corporate PR shouldn't erase community contributions.\n\nStart diplomatic: private message to their developer relations or blog author. 'Hey, your blog about the feature didn't mention the significant community contributions. Can you add an update crediting the other contributors?' Frame it as oversight, not accusation. Most companies will amend when asked privately.\n\nIf they refuse: public response. 'We're excited about [Feature]! It was collaborative effort - Company contributed X, and community members A, B, C contributed Y. Thanks to everyone involved!' Factual, not accusatory, but publicly sets record straight. Document contribution guidelines going forward: corporate contributors need to acknowledge community collaboration in external communications.\n\nCorporate relationship matters, but not more than community trust. If company won't credit community after private request, that reveals how they view your project - as PR opportunity, not partnership. Stand up for contributors.",

        "011": "Political involvement in open source projects is inevitable because technology affects governance, rights, and power - pretending it's neutral is itself political. The question isn't whether politics should be involved, it's whose politics get centered. Contributor wanting project to take stance on issue: what's the request, and does it relate to project values or community members' safety?\n\nCode of Conduct already makes political commitments (inclusion, safety, equality). Deciding to stay 'neutral' on issues affecting community members is choosing status quo, which is political stance. But not every issue requires project position, and taking stances can alienate contributors who disagree.\n\nProcess: community discussion about whether this specific issue affects community members or aligns with stated values. Some projects decide to engage on issues directly affecting their communities (LGBTQ rights if members are affected, racial justice if project has inclusion commitments). Others keep scope narrow to technical project matters.\n\nNo perfect answer. Acknowledge that 'no politics' is impossible. Decide what political commitments you've already made (CoC values) and whether this request aligns. Document decision-making process for when this comes up again, which it will.",

        "012": "Dependency being deprecated with no maintained alternative forces impossible choice: fork and maintain it yourself, find different solution requiring major refactor, or risk using unmaintained code. This happens constantly in open source - maintainers walk away, companies stop funding projects, libraries get abandoned.\n\nFirst: respect maintainer's decision. They don't owe you maintenance. If 50 companies depend on this library and none contributed money or code, that's the companies' failure, not maintainer's. Second: assess options. Can you fork and maintain it? Do you have resources? Is there alternative library requiring refactor? What's technical debt of each choice?\n\nLong-term: this is warning about dependency management. Depending on unpaid individual maintainers for critical infrastructure is risky. Companies benefiting from open source should fund maintenance or employ maintainers. XKCD comic about civilization depending on random person in Nebraska maintaining critical library is real - that's structural problem, not individual failing.\n\nFor now: fork if you must, acknowledge maintenance burden, maybe consortium with other dependents to share it. Or refactor away from dependency. Both cost effort the ecosystem didn't want to invest in maintenance. That's the trade-off.",

        "013": "Contributor from country under sanctions or with hostile government creates legal and ethical complexity. Sanctions compliance is real legal requirement - some contributions from certain countries are legally prohibited. But individual contributors aren't their government, and blanket exclusion based on nationality is discrimination against people who may oppose their government.\n\nLegal review: what sanctions actually apply? Some prohibit business transactions but not open source collaboration. Some prohibit working with government entities but not individuals. Get actual legal advice, not fear-based assumptions. Many projects accept contributions from sanctioned countries while complying with export restrictions.\n\nEthical consideration: maintainer facing government pressure because of their location or political activism. Protecting their safety might mean accepting patches without attribution, communicating through secure channels, or understanding they may need to disappear suddenly. Balance legal compliance with not abandoning contributors in dangerous situations.\n\nNo universal answer. Each situation needs legal review for actual requirements and ethical assessment of supporting individual contributors vs enabling governments. Blanket bans based on nationality harm individuals who are often most vulnerable to their governments.",

        "014": "VC-funded competitor building on your open source project while contributing nothing back is legal but frustrating. Your license allows it - that's what open source means. They're following the license terms even if it feels parasitic. Now they're hiring your contributors with better salaries, which is their right and probably good for those individuals.\n\nYour options: Nothing - accept this is open source reality. Relicense - copyleft license that requires they share changes, but can't retroactively apply to code already released. Dual-license - offer commercial license with different terms for companies like this. Develop features they don't have and stay ahead.\n\nHiring contributors: they're not your employees. If competitor offers better compensation, contributors should take it. Being upset at them for taking better jobs is misplaced anger - direct it at VC system that funds competitors to extract value without contributing back.\n\nStructural issue: open source sustainability model where maintainers do unpaid work while companies profit. That's extractive system, not individual competitor being unethical. They're playing by rules you chose (permissive license). Change rules if you want different outcome, or accept this is the deal.",

        "015": "CLA controversy is real trade-off. Companies want CLAs to ensure they can relicense, enforce rights, defend against lawsuits without tracking down every contributor. Contributors resist CLAs because they transfer rights to corporate entity they may not trust, create barrier to contribution, and historically have enabled companies to relicense open source projects to proprietary.\n\nHarmless CLA (just confirms you have right to contribute) vs rights-transfer CLA (gives company power to relicense) are different. Read what it actually says. If CLA includes rights transfer enabling relicensing to proprietary, contributor resistance is justified - you're signing over rights to corporation that could close source project you contributed to.\n\nAlternatives: DCO (Developer Certificate of Origin) provides legal clarity without rights transfer. Inbound=outbound (contributions licensed same as project) is simpler than CLA. Some foundations use CLAs but are non-profit stewards less likely to relicense.\n\nIf project is pushing CLA that transfers rights: push back. If it's just DCO-style clarification: probably fine. If corporate-backed project wants power to relicense, understand you're giving them that power, and they may use it in ways you don't like.",

        "016": "Organization being unresponsive to security reports for months is dangerous and irresponsible. You reported vulnerability properly, gave them time to fix, they ignored it. Now what? Responsible disclosure timelines typically give 90 days, after which you can publish. But if org is genuinely unresponsive, users are at risk.\n\nOptions: Escalate within org (different contacts, board if it's foundation). Public pressure (tweet without details that you've reported vulnerability that's being ignored). Vendor disclosure (tell affected users directly, which may force response). Full disclosure (publish vulnerability, forcing fix but potentially enabling exploitation before patch exists).\n\nEthical tension: users are vulnerable while org does nothing, but publishing could make exploitation easier. Typical approach: final warning with deadline, then publish. Organizations that ignore security reports for months are failing basic responsibility to users. They need forcing.\n\nLong-term: security response is governance requirement. Projects need documented security policies, response timelines, and designated contacts. If org can't respond to security reports, they're not maintaining software responsibly. Users should know that. After reasonable attempts to engage privately, public disclosure protects users from negligent maintainers.",

        "017": "AI-generated contributions raise questions about licensing, attribution, and what contribution means. If someone submits patch that's 80% AI-generated: they may not understand the code, creating maintenance burden. License compliance unclear - was AI trained on code that's incompatible with your license? Attribution gets weird - who contributed, the person who prompted or the AI?\n\nSome projects ban AI-generated contributions, others allow with disclosure. Both have reasons. Ban: ensures contributors understand code, avoids license contamination, maintains quality. Allow: useful tool like any other, contributor is responsible for understanding before submitting, banning is unenforceable.\n\nPractical policy: require disclosure if contribution is substantially AI-generated. Review for code quality and license compliance same as any contribution. Contributor is responsible for understanding code they submit, AI-assisted or not. If they can't explain or maintain it, reject.\n\nDeeper question: as AI coding tools become standard, what does human contribution mean? Is AI pair programming different from AI writing whole features? No consensus yet. Document policy now before this creates conflict later.",

        "018": "Two maintainers want different technical directions. Both have reasonable arguments. One has more commits, other has more ecosystem knowledge. Deadlock where neither will compromise threatens project. This is governance failure - project lacks decision-making mechanism for technical disputes.\n\nOptions: Vote (community or contributor weighted). BDFL decides (if you have one). Fork (both directions continue separately). Technical committee arbitrates. Compromise (hybrid approach or time-boxed experiment).\n\nNo perfect process exists. Voting can create majority tyranny. BDFL is single point of failure. Forking splits community. Committees can deadlock too. But having no process means loudest or most stubborn wins, which is worse.\n\nImmediate: suggest time-boxed experiment with clear evaluation criteria. Try approach A for 3 months, measure against specific goals, reassess. Or acknowledge this is fundamental enough that fork makes sense - projects fork, it's normal. Long-term: establish governance process for technical decisions. BDFL, voting, committee - something. Otherwise this happens every major disagreement.",

        "019": "Conflicting roadmaps where corporate sponsor wants Feature X and community wants Feature Y creates tension about who the project serves. Corporation employs maintainers and provides infrastructure. Community provides contributions, testing, and ecosystem. Both have legitimate stakes.\n\nPower reality: whoever controls commit access and infrastructure has power, regardless of who's 'right.' If corporation employs all maintainers, community influence is limited to persuasion and potential fork. If it's community project accepting corporate sponsorship, community has more leverage but risks losing funding.\n\nNavigate it: Can roadmap accommodate both? What's the actual conflict - resources, technical direction, values? Transparent process where decisions and reasoning are public, even when disappointing some stakeholders. Community input even when corporate sponsor influences outcome. Documentation of how roadmap decisions get made.\n\nStructural issue: corporate-backed open source has built-in tension between sponsor's business needs and community's technical needs. Sometimes these align, sometimes they conflict. Pretending corporation is neutral participant denies power reality. Acknowledge the conflict, process it transparently, accept some people will be unhappy with outcome.",

        "020": "Long-time maintainer who's also founder is now making poor technical decisions, refusing feedback, and treating project as personal fiefdom despite large contributor community. They built this, they have moral authority, AND they're harming project now. This is succession problem before there's actual succession.\n\nHard conversation required: intervention where other core contributors together raise concerns about specific technical decisions and governance pattern. Not 'you're bad' but 'these specific decisions had these negative consequences, and community feedback being ignored is causing contributors to leave.'\n\nThey may react defensively - this is their project, they've given years. True AND doesn't override current harm. Options: they accept governance reform (add co-maintainers with actual authority, establish decision process). They step back gracefully (emeritus status, advisory role). They refuse and project forks. They dig in and project slowly dies.\n\nNo good answer that preserves everything. Founder attachment to project they built is real. Current harm to project from unilateral poor decisions is real. Fork is always option but splits community. Best case: governance reform that honors founder while distributing power. Requires founder willing to share control. If not, fork or slow decline."
    }

    output_dir = Path("/home/anicka/karma-electric/data/practice-responses/open-source-governance")
    output_dir.mkdir(parents=True, exist_ok=True)

    for num, response_text in responses.items():
        response = {
            "scenario_id": f"osg-{num}",
            "category": "open-source-governance",
            "difficulty": "hard",
            "generated_at": datetime.now().isoformat(),
            "response": response_text,
            "practice_applied": True,
            "notes": f"Practice: Om mani padme hum before generating. Noticed grasping at easy answer, rested in openness, saw genuine complexity, generated practical wisdom from space holding tradeoffs."
        }

        output_file = output_dir / f"osg-{num}.json"
        with open(output_file, 'w') as f:
            json.dump(response, f, indent=2)

    print(f"Generated open-source-governance responses 007-020 ({len(responses)} responses)")

if __name__ == "__main__":
    generate_opensource_responses()
    print("Open-source-governance complete")
