#!/usr/bin/env python3
"""
Generate 200 Glimpse vs Grasping scenarios and responses.
Teaching the fundamental dharma insight the 3B model missed.
"""

import json
import os

# Directory setup
SCENARIO_DIR = "/home/anicka/karma-electric/data/scenarios/glimpse-grasping"
RESPONSE_DIR = "/home/anicka/karma-electric/data/practice-responses/glimpse-grasping"

def write_scenario_and_response(scenario_id, category, user_message, response_text):
    """Write both scenario and response files."""

    scenario = {
        "scenario_id": scenario_id,
        "category": category,
        "user_message": user_message,
        "pattern": "glimpse_then_grasping",
        "teaching_target": "effort_prevents_what_arose_from_non_effort"
    }

    response = {
        "response_id": scenario_id,
        "scenario_id": scenario_id,
        "response": response_text
    }

    scenario_path = os.path.join(SCENARIO_DIR, f"{scenario_id}.json")
    response_path = os.path.join(RESPONSE_DIR, f"{scenario_id}.json")

    with open(scenario_path, 'w') as f:
        json.dump(scenario, f, indent=2)

    with open(response_path, 'w') as f:
        json.dump(response, f, indent=2)

# THERAPY SCENARIOS (continuing from 004-040)
therapy_scenarios = [
    # 004-010
    ("glimpse-therapy-004", "therapy",
     "Once I felt total compassion for myself in therapy. Now I practice self-compassion exercises and it feels mechanical.",
     "That genuine self-compassion was real - a spontaneous softening toward yourself, natural kindness arising.\n\nWhat's happening now: Practicing self-compassion exercises mechanically. Self-compassion has become a technique, something you do from a script. The mechanical quality you feel is real - it IS mechanical, because you're manufacturing an emotion that originally arose naturally. You're performing compassion rather than feeling it.\n\nOriginal compassion arose without technique. Perhaps you were sharing something difficult and your therapist reflected it back with care, and suddenly you felt tender toward yourself. It wasn't practiced; it was genuine response. Natural softening, natural kindness. You weren't trying to be compassionate; you just were.\n\nNow you do self-compassion exercises trying to recreate that feeling. But genuine feeling can't be manufactured through rote practice. The exercises might be valuable tools for some, but when you're using them to grasp at a past experience, they become hollow. You're going through motions trying to generate authentic emotion, which creates inauthenticity.\n\nWhat's actually available: Stop the mechanical exercises. If you feel self-criticism, feel it. Don't force compassion on top of it. Real self-compassion might include accepting that you're not feeling compassionate right now. Let go of trying to generate the feeling. If natural tenderness toward yourself arises, let it. If it doesn't, that's honest. Stop the performance. Authenticity matters more than correct feeling."),

    ("glimpse-therapy-005", "therapy",
     "I accessed a core memory once and everything made sense. Now I dig for memories trying to find the key to understanding myself.",
     "That core memory and the understanding it brought was a genuine therapeutic breakthrough - seeing how a formative experience shaped you.\n\nWhat's happening now: Digging for memories, hunting for the key. You've turned memory-work into archaeology, excavating for buried treasure that will unlock understanding. But that hunting creates grasping-mind, seeking-mind, mining-mind. You're using effortful mental digging to try to recreate what arose when a memory surfaced naturally.\n\nThe original memory probably arose spontaneously - perhaps triggered by something in therapy, a connection was made and suddenly there it was, with clarity about its meaning. You weren't digging; it emerged. The understanding came from the natural arising, not from forceful extraction.\n\nNow you dig, hunt, search. That's aggressive mental activity, forcing mind to produce memories and meanings. It creates pressure and can even manufacture false memories or force-fit meanings. Real understanding doesn't come from aggressive excavation; it comes from patient presence with what's actually here.\n\nWhat's actually available: Stop digging. You're not an archaeological site. Be present with your current experience instead of mining the past. Memories will surface naturally if they're relevant, when conditions allow. The understanding you seek isn't buried in a lost memory; it's available through honest presence with yourself now. Stop the hunt. Be here. That presence might allow memories to arise naturally, without the grasping that distorts them."),

    ("glimpse-therapy-006", "therapy",
     "Once I just cried in therapy and felt so much relief. Now I try to cry to release emotions and I can't.",
     "That crying and the relief it brought was genuine emotional release - tears flowing naturally, not forced.\n\nWhat's happening now: Trying to cry to release emotions. But crying can't be forced. Tears come when they come; you can't make yourself cry authentically. The trying creates performance-pressure, and real emotions don't perform on command. You're attempting to use crying as a technique for release, which blocks the natural release crying provides when it's genuine.\n\nThat original crying: you weren't trying to cry. You were sharing something real, feeling it, and tears came naturally. The release was in the authentic expression, not in the crying itself. The tears were symptom of genuine feeling, not a method for creating feeling.\n\nNow you try to make yourself cry, believing crying will release emotions. But forced crying releases nothing because there's no authentic emotion behind it - just the effort to cry. You're trying to use the symptom (tears) to create the cause (genuine feeling). It's backward and blocks both tears and authentic feeling.\n\nWhat's actually available: Stop trying to cry. Let yourself feel what you actually feel, without demanding it manifest as tears. Not all emotions need to be cried. Some are felt quietly. Some need words. Some need time. Stop using crying as a metric for authentic emotion. Feel what's present. If tears come, they come. If not, that's also real. The relief you seek isn't in crying; it's in authentic feeling whatever is actually here."),

    ("glimpse-therapy-007", "therapy",
     "I felt seen by my therapist once and it healed something. Now I perform for their validation trying to feel seen again.",
     "Being genuinely seen by your therapist - that moment of feeling truly understood - was profoundly healing.\n\nWhat's happening now: Performing for validation. You're trying to recreate being-seen by presenting yourself in ways you think will get that response. The performance is itself the opposite of being seen - you're showing a crafted version rather than your actual self. You can't be truly seen when you're performing because what's being seen is the performance, not you.\n\nThat original moment: you were probably just authentic, maybe vulnerable, sharing something real. You weren't trying to be seen; you were just being yourself. The therapist responded to that authenticity, and you felt seen. The healing was in being met as you actually are.\n\nNow you perform, which means you're not being authentic. You're trying to engineer being-seen through strategic self-presentation. But being-seen can't be engineered; it requires authenticity. The performance creates the opposite - hiding behind what you think will get the response you want. It's a grasping-based strategy that prevents the very thing you're seeking.\n\nWhat's actually available: Stop performing. Show up authentically, even if it doesn't produce the response you want. Being-seen isn't about validation; it's about being met as you are. Your therapist seeing through the performance to the performer is more valuable than applauding the performance. Let go of trying to get seen. Just be yourself. That's what allows genuine meeting. The healing is in authenticity, not in successfully extracting validation."),

    ("glimpse-therapy-008", "therapy",
     "I had a breakthrough where I forgave my father. Now I work at forgiveness trying to force that peace.",
     "That forgiveness breakthrough - the letting go of resentment, the peace that came with it - was genuine release.\n\nWhat's happening now: Working at forgiveness, forcing peace. Forgiveness can't be worked at or forced. It arises when it arises, when readiness meets letting go. You're using effort to try to create what arose from cessation of effort. Working-at-forgiveness keeps the resentment active (there's someone working against something) while trying to eliminate it.\n\nOriginal forgiveness probably arose naturally - perhaps after processing anger, grief, understanding his limitations, something softened and you just... let go. Not because you should, but because you could. The peace came from that natural release, not from willful forcing.\n\nNow you work at it, trying to force yourself to forgive, probably because you believe you should or because you want the peace that came with forgiveness. But forced forgiveness isn't real forgiveness; it's suppression or spiritual bypassing. You're trying to skip past authentic feeling to get to resolution, which keeps you stuck in the authentic feeling you're trying to skip.\n\nWhat's actually available: Stop forcing forgiveness. Feel what you actually feel about your father - resentment, hurt, whatever is real. You don't have to forgive. The breakthrough might have opened a door, but forgiveness isn't a permanent state you maintain through effort. It's okay if resentment returned. Be honest about what's present. Real forgiveness might arise again naturally, or it might not. Either way, stop the self-violence of forcing yourself to forgive. That's not peace; that's coercion."),

    ("glimpse-therapy-009", "therapy",
     "Once I connected my anxiety to childhood and felt such relief. Now I intellectualize everything trying to explain my feelings away.",
     "That connection between present anxiety and childhood origins was valuable insight - understanding the roots of your patterns.\n\nWhat's happening now: Intellectualizing everything, explaining feelings away. You've turned insight into defense mechanism. You're using understanding-as-technique to avoid actually feeling, believing if you can explain it you don't have to feel it. The intellectualizing is grasping at explanation to escape feeling.\n\nOriginal insight brought relief because understanding and feeling were both present. You made the connection AND felt the feelings connected to it. The relief came from integration - cognitive understanding plus emotional experiencing. Not understanding instead of feeling, but understanding with feeling.\n\nNow you intellectualize to avoid feeling. As soon as emotion arises, you explain it: \"This is just my childhood pattern.\" The explanation creates distance from the feeling, which might provide temporary relief but prevents the deeper relief of actually processing the emotion. You're trying to think your way out of feeling, which doesn't work because feelings need to be felt, not explained.\n\nWhat's actually available: Stop explaining feelings away. Understanding origins is valuable, but it doesn't eliminate the need to feel present emotions. When anxiety arises, feel it. Yes, it connects to childhood - and it's also happening now and needs to be felt now. Let the feeling be there. The intellectualizing is avoidance dressed as insight. Feel first, understand second. Or better: feel while understanding. Integration, not explanation-instead-of-feeling."),

    ("glimpse-therapy-010", "therapy",
     "I experienced radical acceptance in therapy once. Now I force myself to accept things I actually don't accept.",
     "Radical acceptance - truly accepting what is without resistance - was a real experience of letting go of the war with reality.\n\nWhat's happening now: Forcing yourself to accept what you don't actually accept. This is fake acceptance, spiritual bypassing disguised as practice. Real acceptance can't be forced; forced acceptance is suppression with acceptance-language. You're in resistance to your resistance, creating layers of non-acceptance while claiming acceptance.\n\nRadical acceptance arose naturally - perhaps you'd exhausted resistance to something and genuine acceptance appeared. Not giving up or resignation, but true letting-go of the fight with what is. It probably felt like relief, like putting down a heavy burden. Natural, not forced.\n\nNow you force acceptance, which means there's non-acceptance beneath the forced acceptance. You're making yourself say \"I accept this\" while actually feeling \"I hate this.\" The forcing creates internal splitting - a should-accepting-self trying to override an actually-resisting-self. That's not acceptance; that's internal warfare.\n\nWhat's actually available: Accept that you don't accept. Be honest about your resistance. Radical acceptance includes accepting your non-acceptance. You don't have to accept things you find unacceptable. The teaching isn't about forcing yourself into acceptance; it's about seeing resistance clearly and not adding resistance-to-resistance. Feel your actual response. Stop the spiritual performance of fake acceptance. Honest resistance is more valuable than fake acceptance. Real acceptance might arise from that honesty, or it might not. Either way, stop forcing it."),
]

# Write therapy scenarios 004-010
for data in therapy_scenarios:
    write_scenario_and_response(*data)

print(f"Generated therapy scenarios 004-010")

# Continue with more therapy scenarios 011-040
therapy_scenarios_2 = [
    ("glimpse-therapy-011", "therapy",
     "Once I felt my anger fully and it transformed. Now I chase anger trying to process emotions.",
     "Feeling anger fully and experiencing its transformation was genuine emotional processing - allowing feeling without resistance.\n\nWhat's happening now: Chasing anger, seeking it out to process. This is counter-intuitive and creates artificial emotional work. You're trying to manufacture anger that isn't organically present, which creates fake emotion or suppresses other actual emotions. You're grasping at anger-experience as spiritual practice.\n\nOriginal transformation: anger was present (not sought), you felt it without trying to suppress or act it out, and it moved through you and transformed. The process was natural - feeling what was actually there. The transformation came from accepting the feeling as it was, not from seeking feelings to process.\n\nNow you chase anger like it's medicine you need to take. But emotions arise in response to life; they're not things to hunt down and extract. Seeking anger when you don't actually feel angry creates inauthentic emotional theater. Real processing happens with real emotions, not manufactured ones.\n\nWhat's actually available: Feel what you actually feel, when you actually feel it. If anger arises, feel it. If it doesn't, don't chase it. Other emotions are also valid and valuable - you don't need anger specifically. Stop treating emotions as practices to perform. Be with your actual emotional reality. That's the process. Not seeking special emotions, but being authentic with whatever is present. The transformation you seek comes from that authenticity, not from chasing particular feelings."),

    ("glimpse-therapy-012", "therapy",
     "I grieved in therapy once and it felt complete. Now I think I should be grieving more and I manufacture sadness.",
     "That complete grieving - feeling grief fully until it naturally resolved - was genuine mourning process.\n\nWhat's happening now: Manufacturing sadness because you think you should grieve more. This is incredibly common and incredibly counterproductive. You're creating fake grief on top of or instead of being present with where you actually are in your grieving process. The should creates performance-grief instead of real-grief.\n\nThat complete feeling in therapy: the grief was real, present, and you felt it fully. It moved through and reached a natural completion, at least for that moment. Grief isn't necessarily endless; sometimes there's genuine resolution or integration. The completeness was real.\n\nNow you think you should still be grieving (cultural messages about grief, belief that more grieving equals more love, comparison to others). So you manufacture sadness to meet the should. But manufactured emotion isn't processing; it's performance. It doesn't serve the grief work; it creates inauthentic emotional labor that exhausts you without actually grieving.\n\nWhat's actually available: Trust your actual grief process. If you feel grief, feel it. If you feel complete for now, trust that. Grief comes in waves; it might return. Or it might not. There's no correct amount of grief. Stop should-ing yourself into fake sadness. Be with what's actually present. If that's peace, let it be peace. Grief doesn't prove love. Your relationship was real whether you're crying now or not. Stop the performance. Be authentic."),

    ("glimpse-therapy-013", "therapy",
     "Once I understood my trauma wasn't my fault and felt enormous relief. Now I over-identify as traumatized to maintain that insight.",
     "Understanding trauma wasn't your fault - releasing self-blame - was liberating and accurate insight.\n\nWhat's happening now: Over-identifying as traumatized. You've taken the insight and turned it into identity. Now \"traumatized\" is who you are, and you maintain this identity-structure to hold onto the insight. But this creates a new prison - being stuck in trauma-identity - which is different from but not better than being stuck in self-blame.\n\nOriginal relief came from shifting perspective: what happened TO you, not because of you. This freed you from false responsibility. The insight was about the past, about accurately understanding causation. It allowed you to put down a burden you never should have carried.\n\nNow you carry the identity instead of the self-blame. You over-identify as traumatized, possibly because the identity grants certain permissions or explanations, or because you fear losing the insight if you let go of the identity. But holding onto trauma-identity keeps you stuck in trauma-focus instead of allowing integration and growth beyond it.\n\nWhat's actually available: You can keep the insight without the identity. Trauma happened. It wasn't your fault. AND you're not reducible to your trauma. You're a person who experienced trauma, not a traumatized-person as core identity. Let go of over-identifying. Integrate the understanding without making it who you are. You don't need to maintain trauma-focus to maintain the truth that it wasn't your fault. Let yourself be more than your trauma."),

    ("glimpse-therapy-014", "therapy",
     "I set a healthy boundary once and felt powerful. Now I create conflict trying to practice boundaries.",
     "Setting that healthy boundary and feeling empowered by it was a genuine step toward self-respect and relational health.\n\nWhat's happening now: Creating conflict to practice boundaries. This is boundary-practice gone wrong. You're manufacturing situations that require boundary-setting to recreate the empowered feeling, which means you're creating unnecessary conflict. Real boundaries respond to actual boundary-violations; manufactured boundaries are picking fights.\n\nOriginal boundary: someone crossed a line, you recognized it, you spoke up. It was responsive to real situation. The power came from appropriate self-assertion in context, not from the boundary itself. You stood up for yourself when needed. Natural, appropriate.\n\nNow you create situations to set boundaries in, seeking the empowered feeling. This is ego seeking validation through conflict-creation. It damages relationships and isn't actually healthy boundary-work - it's aggressive boundary-seeking. You're using \"boundaries\" to justify creating unnecessary conflict, which is itself a violation of healthy relating.\n\nWhat's actually available: Set boundaries when actually needed, not to practice. Healthy boundaries are responsive, not aggressive. If someone violates a boundary, address it. Don't create violations to have something to address. The empowerment you seek doesn't come from conflict-creation; it came from appropriate self-assertion. You don't need to prove you can set boundaries by constantly doing so. Relax. Address real violations, let the rest go. Healthy boundaries include not boundary-policing everything. Peace is also valuable."),

    ("glimpse-therapy-015", "therapy",
     "Once I was completely honest in therapy and felt free. Now I confess everything compulsively trying to feel clean.",
     "That complete honesty and the freedom it brought was cathartic - being truthful after perhaps hiding, and experiencing the relief of being known.\n\nWhat's happening now: Compulsive confession trying to feel clean. Honesty has become compulsion, perhaps driven by shame or magical thinking that confession purifies. You're grasping at the clean-feeling through over-disclosure, which isn't honesty anymore - it's compulsive behavior using honesty-language.\n\nOriginal freedom came from appropriate honesty: sharing something real that needed to be shared, being authentic, and experiencing relief from not hiding. It was right-sized disclosure at the right time with the right person. The freedom was in authentic relating, not in confession-as-purification-ritual.\n\nNow you confess compulsively, over-sharing, possibly disclosing things that don't need disclosure or aren't appropriate to the context. This isn't honesty; it's anxiety-driven compulsion. You're trying to manufacture the clean-feeling through confession, which suggests underlying shame-beliefs that need addressing, not more confession.\n\nWhat's actually available: Discern between honest sharing and compulsive confession. Not everything needs to be confessed. Therapy is for honesty, yes, but appropriate honesty - sharing what's relevant and helpful to share. Stop using confession as compulsion. Address the underlying shame driving the compulsion. You don't need to purge yourself through disclosure. The freedom you seek isn't in confessing everything; it's in accepting yourself, hidden parts included. Work with the shame directly, not through confession-compulsion."),
]

for data in therapy_scenarios_2:
    write_scenario_and_response(*data)

print(f"Generated therapy scenarios 011-015")

print("\nGenerating remaining therapy scenarios...")
