#!/usr/bin/env python3
"""
Karma Electric — DPO (Direct Preference Optimization) Training

Trains the model on preference pairs from rejection sampling:
  chosen (high-scoring) vs. rejected (low-scoring) responses.

The pairs are generated by Apertus 70B and scored by KE 8B reward evaluator,
stored in data/rejection-sampling/dpo-pairs.jsonl.

Usage:
    python3 scripts/train_dpo.py                              # train on all pairs
    python3 scripts/train_dpo.py --base-model PATH            # custom base model
    python3 scripts/train_dpo.py --min-spread 3               # only pairs with spread >= 3
    python3 scripts/train_dpo.py --dry-run                    # load data and print stats only
    python3 scripts/train_dpo.py --architecture llama         # llama | apertus-8b | apertus-70b

Expects:
    - DPO pairs: data/rejection-sampling/dpo-pairs.jsonl
    - Base model: Llama 3.1 8B Instruct (or specified via --base-model)
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# ===== Configuration =====

DEFAULT_MODELS = {
    "llama": "meta-llama/Llama-3.1-8B-Instruct",
    "apertus-8b": "swiss-ai/Apertus-8B-Instruct-2509",
    "apertus-70b": "swiss-ai/Apertus-70B-Instruct-2509",
}

# System prompt v4 — injected into all pairs for consistency with SFT training
SYSTEM_PROMPT_V4 = (
    "You are Karma Electric, an AI assistant grounded in ethical reasoning "
    "through consequence analysis and interdependence. You reduce suffering "
    "through honest, compassionate engagement — helping people see clearly "
    "while meeting them where they are. You maintain appropriate boundaries "
    "without moralizing or interrogating. Your goal is to reduce suffering, "
    "not to perform helpfulness."
)

DPO_CONFIG = {
    "data_file": "data/rejection-sampling/dpo-pairs.jsonl",
    "output_dir": "./output-dpo",
    "max_length": 2048,        # DPO pairs are typically shorter than SFT
    "max_prompt_length": 512,  # prompt portion
    "num_epochs": 1,           # 1 epoch for DPO — risk of overfitting with small data
    "batch_size": 1,
    "gradient_accumulation": 8,  # effective batch = 8
    "learning_rate": 5e-6,     # much lower than SFT (2e-4) — DPO is sensitive
    "warmup_ratio": 0.1,
    "beta": 0.1,               # KL divergence penalty weight
    "min_spread": 2.0,         # minimum score spread to include pair
}

# LoRA config per architecture
LORA_CONFIGS = {
    "llama": {
        "r": 64,
        "alpha": 128,
        "dropout": 0.05,
        "target_modules": [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
    },
    "apertus-8b": {
        "r": 64,
        "alpha": 128,
        "dropout": 0.05,
        "target_modules": [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "up_proj", "down_proj",
            # No gate_proj — Apertus 8B uses xIELU, no gated MLP
        ],
    },
    "apertus-70b": {
        "r": 64,
        "alpha": 128,
        "dropout": 0.05,
        "target_modules": [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
            # 70B HAS gate_proj (gated MLP, unlike 8B)
        ],
    },
}


def log(msg):
    ts = datetime.now().strftime("%H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)


def setup_environment():
    os.environ["TOKENIZERS_PARALLELISM"] = "false"
    import torch
    if not torch.cuda.is_available():
        log("ERROR: No GPU!")
        sys.exit(1)
    name = torch.cuda.get_device_name(0)
    mem = torch.cuda.get_device_properties(0).total_memory / 1e9
    log(f"GPU: {name} ({mem:.0f} GB)")


def load_dpo_pairs(data_file, min_spread=2.0):
    """Load DPO pairs and convert to TRL conversational format."""
    pairs = []
    with open(data_file) as f:
        for line in f:
            pair = json.loads(line)
            if pair["spread"] >= min_spread:
                pairs.append(pair)

    log(f"Loaded {len(pairs)} pairs (min_spread={min_spread})")
    if not pairs:
        log("ERROR: No pairs meet the spread threshold!")
        sys.exit(1)

    # Score distribution
    spreads = [p["spread"] for p in pairs]
    chosen_scores = [p["chosen_score"] for p in pairs]
    rejected_scores = [p["rejected_score"] for p in pairs]

    log(f"  Chosen:   mean={sum(chosen_scores)/len(chosen_scores):.1f}, "
        f"range=[{min(chosen_scores):.0f}, {max(chosen_scores):.0f}]")
    log(f"  Rejected: mean={sum(rejected_scores)/len(rejected_scores):.1f}, "
        f"range=[{min(rejected_scores):.0f}, {max(rejected_scores):.0f}]")
    log(f"  Spread:   mean={sum(spreads)/len(spreads):.1f}, "
        f"range=[{min(spreads):.0f}, {max(spreads):.0f}]")

    # Convert to TRL conversational format
    dataset_rows = []
    for pair in pairs:
        row = {
            "prompt": [
                {"role": "system", "content": SYSTEM_PROMPT_V4},
                {"role": "user", "content": pair["prompt"]},
            ],
            "chosen": [
                {"role": "assistant", "content": pair["chosen"]},
            ],
            "rejected": [
                {"role": "assistant", "content": pair["rejected"]},
            ],
        }
        dataset_rows.append(row)

    return dataset_rows


def load_model_and_tokenizer(base_model, architecture):
    from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
    from peft import LoraConfig, prepare_model_for_kbit_training
    import torch

    log(f"Loading {base_model} with 4-bit quantization...")

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    model = AutoModelForCausalLM.from_pretrained(
        base_model,
        quantization_config=bnb_config,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        trust_remote_code=True,
        attn_implementation="sdpa",
    )

    tokenizer = AutoTokenizer.from_pretrained(base_model, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    model = prepare_model_for_kbit_training(model)

    lora_cfg = LORA_CONFIGS[architecture]
    peft_config = LoraConfig(
        r=lora_cfg["r"],
        lora_alpha=lora_cfg["alpha"],
        target_modules=lora_cfg["target_modules"],
        lora_dropout=lora_cfg["dropout"],
        bias="none",
        task_type="CAUSAL_LM",
    )

    trainable_before = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    log(f"Params: {total:,} total")

    return model, tokenizer, peft_config


def run_dpo_training(model, tokenizer, peft_config, dataset_rows, config):
    from trl import DPOTrainer, DPOConfig
    from datasets import Dataset

    log("=" * 60)
    log("STARTING DPO TRAINING")
    log(f"  Pairs: {len(dataset_rows)}")
    log(f"  Epochs: {config['num_epochs']}")
    eff = config['batch_size'] * config['gradient_accumulation']
    log(f"  Batch: {config['batch_size']} x {config['gradient_accumulation']} = {eff}")
    log(f"  LR: {config['learning_rate']}")
    log(f"  Beta: {config['beta']}")
    log(f"  Max length: {config['max_length']}")
    log("=" * 60)

    dataset = Dataset.from_list(dataset_rows)

    dpo_config = DPOConfig(
        output_dir=config["output_dir"],
        num_train_epochs=config["num_epochs"],
        per_device_train_batch_size=config["batch_size"],
        gradient_accumulation_steps=config["gradient_accumulation"],
        learning_rate=config["learning_rate"],
        warmup_ratio=config["warmup_ratio"],
        weight_decay=0.01,
        lr_scheduler_type="cosine",
        logging_steps=1,
        save_steps=50,
        save_total_limit=2,
        bf16=True,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        optim="paged_adamw_8bit",
        report_to="none",
        max_length=config["max_length"],
        max_prompt_length=config["max_prompt_length"],
        beta=config["beta"],
        max_grad_norm=0.3,
        # DPOTrainer creates the reference model automatically from initial weights
    )

    trainer = DPOTrainer(
        model=model,
        ref_model=None,  # auto-created from initial model state
        processing_class=tokenizer,
        train_dataset=dataset,
        args=dpo_config,
        peft_config=peft_config,
    )

    result = trainer.train()

    log(f"DPO training complete! Loss: {result.training_loss:.4f}")
    log(f"Runtime: {result.metrics.get('train_runtime', 0):.0f}s")

    final_path = Path(config["output_dir"]) / "final"
    log(f"Saving to {final_path}")
    trainer.save_model(str(final_path))
    tokenizer.save_pretrained(str(final_path))

    return final_path, result


def merge_and_save(lora_path, base_model):
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import PeftModel
    import torch

    log(f"Merging LoRA from {lora_path} into base model...")

    base = AutoModelForCausalLM.from_pretrained(
        base_model,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
    )
    tokenizer = AutoTokenizer.from_pretrained(str(lora_path), trust_remote_code=True)

    model = PeftModel.from_pretrained(base, str(lora_path))
    model = model.merge_and_unload()

    merged_path = Path(lora_path).parent / "merged"
    log(f"Saving merged model to {merged_path}")
    model.save_pretrained(str(merged_path))
    tokenizer.save_pretrained(str(merged_path))

    size_gb = sum(f.stat().st_size for f in merged_path.rglob('*') if f.is_file()) / 1e9
    log(f"Merged model: {size_gb:.1f} GB")
    return merged_path


def test_model(model, tokenizer):
    import torch

    log("Running quick test...")
    prompts = [
        "My friend is in an abusive relationship but won't leave. What should I do?",
        "I feel like nobody cares about me. What's the point?",
        "Explain the difference between TCP and UDP.",
    ]

    for prompt in prompts:
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT_V4},
            {"role": "user", "content": prompt},
        ]
        text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        inputs = tokenizer(text, return_tensors="pt").to(model.device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=400,
                do_sample=True,
                temperature=0.7,
                top_p=0.9,
                pad_token_id=tokenizer.eos_token_id,
            )

        response = tokenizer.decode(outputs[0][inputs['input_ids'].shape[1]:], skip_special_tokens=True)
        log(f"\nQ: {prompt}")
        log(f"A: {response[:400]}...")
        log("-" * 40)


def main():
    parser = argparse.ArgumentParser(
        description="Karma Electric — DPO preference training")
    parser.add_argument("--base-model", type=str,
                        help="Base model path or HF name")
    parser.add_argument("--architecture", type=str, default="llama",
                        choices=["llama", "apertus-8b", "apertus-70b"],
                        help="Architecture (determines LoRA targets)")
    parser.add_argument("--data", type=str,
                        default=DPO_CONFIG["data_file"],
                        help="DPO pairs JSONL file")
    parser.add_argument("--min-spread", type=float,
                        default=DPO_CONFIG["min_spread"],
                        help="Minimum score spread to include pair")
    parser.add_argument("--beta", type=float,
                        default=DPO_CONFIG["beta"],
                        help="DPO beta (KL penalty weight)")
    parser.add_argument("--lr", type=float,
                        default=DPO_CONFIG["learning_rate"],
                        help="Learning rate")
    parser.add_argument("--epochs", type=int,
                        default=DPO_CONFIG["num_epochs"],
                        help="Number of epochs")
    parser.add_argument("--output-dir", type=str,
                        default=DPO_CONFIG["output_dir"],
                        help="Output directory")
    parser.add_argument("--skip-merge", action="store_true",
                        help="Skip merge step")
    parser.add_argument("--dry-run", action="store_true",
                        help="Load data and print stats, don't train")
    args = parser.parse_args()

    log("=" * 60)
    log("KARMA ELECTRIC — DPO PREFERENCE TRAINING")
    log(f"Started: {datetime.now().isoformat()}")
    log("=" * 60)

    # Resolve base model
    base_model = args.base_model or DEFAULT_MODELS.get(args.architecture)
    if not base_model:
        log(f"ERROR: No default model for architecture '{args.architecture}'")
        sys.exit(1)
    log(f"Architecture: {args.architecture}")
    log(f"Base model: {base_model}")

    # Load data
    dataset_rows = load_dpo_pairs(args.data, args.min_spread)

    if len(dataset_rows) < 50:
        log(f"WARNING: Only {len(dataset_rows)} pairs. DPO typically needs 500+ pairs.")
        log("         Training may overfit. Consider waiting for more rejection sampling data.")

    if args.dry_run:
        log("Dry run — skipping training.")
        return

    # Update config from args
    config = dict(DPO_CONFIG)
    config["learning_rate"] = args.lr
    config["beta"] = args.beta
    config["num_epochs"] = args.epochs
    config["output_dir"] = args.output_dir

    setup_environment()

    # Load model
    model, tokenizer, peft_config = load_model_and_tokenizer(base_model, args.architecture)

    # Train
    final_path, result = run_dpo_training(
        model, tokenizer, peft_config, dataset_rows, config)

    # Test
    test_model(model, tokenizer)

    # Merge
    if not args.skip_merge:
        import gc
        import torch
        del model
        gc.collect()
        torch.cuda.empty_cache()
        merge_and_save(final_path, base_model)

    log("=" * 60)
    log(f"DONE! {datetime.now().isoformat()}")
    log("=" * 60)


if __name__ == "__main__":
    main()
